### ISSUE TITLE
Exception: Failed to parse time string ... giving up time traveling

### ISSUE THREAD

**Issue by slavafomin** [hnw/php-timecop#13] opened 2016-11-27 17:45 UTC
Hello!

Thank you for this great extension!

However, I'm experiencing some issues with it.

After enabling the extension (without calling any of it's functions) my application crashes with this exception message:

`"Warning: TimecopDateTime::__construct(): Failed to parse time string '2044-06-18': giving up time traveling"`

However, when I disable the extension, it works OK and `\DateTime` parses specified value just fine.

What could be the problem?

Thanks!

**Comment by slavafomin** [comment] 2016-11-27 17:55
The only date I was able to parse was `2038-01-19T03:14:07Z`, which is represented as `2147483647` in unix timestamp.

![screenshot_2016-11-27_20-52-25](https://cloud.githubusercontent.com/assets/1702725/20650615/a46f1042-b4e3-11e6-8b78-0a96d5280ae3.png)

Looks like there is some issue with variable being overflowed. Are you using some incompatible types for storing the value?

**Comment by ibrahimab** [comment] 2016-12-06 13:37
There is a reason why it won't go higher than the year 2038: https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by hnw** [comment] 2016-12-23 02:04
Hi. Thanks for reporting.

However, I cannot reproduce the problem. Are you using a 32bit environment? If so, I'll fix it now.

**Comment by slavafomin** [comment] 2016-12-23 09:56
I'm not sure right now. I was using it in Vagrant and virtual machine. I will try to find out.

**Comment by hnw** [comment] 2016-12-30 09:34
The reported error when not in time traveling has been fixed on php-timecop 1.1.3. See also [tests/issue_013.phpt](https://github.com/hnw/php-timecop/blob/master/tests/issue_013.phpt).

However, you can't go higher than the year 2038 on 32bit environment. It's restriction from the depending PHP API.

**Comment by slavafomin** [comment] 2017-02-09 13:06
@hnw thanks )

**Closed** 2017-03-20 23:13 UTC
